---

- name: Copying Launcher to /usr/local/bin 
  copy: src=group_vars/mining/launcher.sh dest=/usr/local/bin/
  become: yes

- file: path=/usr/local/bin/launcher.sh mode="a+rx"
  become: yes

- copy: src=group_vars/mining/miner.service dest=/etc/systemd/system
  become: yes

- name: Change sudo session timeout
  become: yes
  lineinfile:
    dest: /etc/sudoers.d/kobr4-sudoers
    line: 'kobr4 ALL = NOPASSWD:/sbin/reboot'
    create: yes
    owner: root 
    group: root 
    mode: "0440"
    state: present
    validate: 'visudo -c -f %s'  

- command: systemctl enable miner.service
  become: yes

- cron:
    name: "Reboot every 12h"
    minute: "0"
    hour: "0,12"
    job : "/sbin/reboot"
    state : absent
  become: yes

#    name: miner
#    enabled: yes
#    masked: no
